spring.application.name=messenger
# Включаем консоль H2 (доступна по адресу http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Настройка создания таблиц
spring.jpa.hibernate.ddl-auto=update